### ISSUE TITLE
Plugin appears to attempt schema verification even when NONE specificed

### ISSUE THREAD

**Issue by ryansmith4** [archiecobbs/hibernate-jpa-schemagen#1]
I've been trying to prevent schema verification using the specified NONE value for verifyFile, but the 6.4.0 plugin seems to treat the NONE value as an actual file.  From looking at the plugin's code, it should ignore the verification step, but somehow does not (at least for me) - any ideas?

![image](https://github.com/archiecobbs/hibernate-jpa-schemagen/assets/1023965/6a887a63-8c78-4751-a0e3-df23a02aa4aa)

**Comment by archiecobbs** [comment]
The change that added support for `NONE` is not included in hibernate-jpa-schemagen version 6.4.0.

I've just released version 6.4.1 which includes it, so upgrading should fix the problem.

Let me know if you have any further issues.

**Comment by ryansmith4** [comment]
@archiecobbs  - confirmed - the new release works perfectly - thank you.
